const nodemailer = require('nodemailer');

const transporter = nodemailer.createTransport({
  host:   process.env.MAIL_HOST,
  port:   parseInt(process.env.MAIL_PORT),
  secure: false,
  auth: {
    user: process.env.MAIL_USER,
    pass: process.env.MAIL_PASS
  }
});

async function sendAlertEmail(agent, patientInput) {
  if (agent.decision !== 'ALERT') return null;
  if (!agent.email_subject || !agent.email_body) return null;

  const mailOptions = {
    from:    `"AI Recovery System" <${process.env.MAIL_USER}>`,
    to:      process.env.MAIL_ALERT_TO,
    subject: agent.email_subject,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px;">
        <h2 style="color: #d32f2f;">Recovery Alert</h2>

        <table style="width:100%; border-collapse: collapse; margin-bottom: 16px;">
          <tr>
            <td style="padding: 6px; font-weight: bold;">Patient ID</td>
            <td style="padding: 6px;">${patientInput.patient_id}</td>
          </tr>
          <tr style="background:#f5f5f5;">
            <td style="padding: 6px; font-weight: bold;">Procedure</td>
            <td style="padding: 6px;">${patientInput.procedure_type}</td>
          </tr>
          <tr>
            <td style="padding: 6px; font-weight: bold;">Recovery Week</td>
            <td style="padding: 6px;">${patientInput.current_week}</td>
          </tr>
          <tr style="background:#f5f5f5;">
            <td style="padding: 6px; font-weight: bold;">Alert Reason</td>
            <td style="padding: 6px; color: #d32f2f;">${agent.alert_reason}</td>
          </tr>
        </table>

        <div style="background: #fff3e0; padding: 12px; border-left: 4px solid #ff9800; margin-bottom: 16px;">
          <strong>Clinical Summary:</strong><br/>
          ${agent.email_body}
        </div>

        <div style="background: #e8f5e9; padding: 12px; border-left: 4px solid #4caf50;">
          <strong>Recommended Action:</strong><br/>
          ${agent.recommended_action}
        </div>

        <hr style="margin-top: 24px;"/>
        <p style="color: #999; font-size: 12px;">
          This alert was generated by the AI Recovery Prediction System.
          Agent reasoning: ${agent.reasoning}
        </p>
      </div>
    `
  };

  const info = await transporter.sendMail(mailOptions);
  console.log(`Alert email sent: ${info.messageId}`);
  return info.messageId;
}

module.exports = { sendAlertEmail };
